export default Object.freeze({
  LOGIN_SCREEN: 'LOGIN',
  RETRIEVE_ACCOUNT_SCREEN: 'RETRIEVE_ACCOUNT_SCREEN',
  CHECK_YOUR_MAIL_SCREEN: 'CHECK_YOUR_MAIL_SCREEN',
  ONBOARDING_SCREEN_1: 'ONBOARDING_SCREEN_1',
  ONBOARDING_SCREEN_2: 'ONBOARDING_SCREEN_2',
  CHANGE_PASSOWRD_SCREEN: 'CHANGE_PASSOWRD_SCREEN',

  HOME_BOTTOM_TABS_NAVIGATOR: 'HOME_BOTTOM_TABS_NAVIGATOR',
  BOOKINGS_SCREEN: 'BOOKINGS_SCREEN',
  MY_HUB_SCREEN: 'MY_HUB_SCREEN',
  ACTIVITY_SCREEN: 'ACTIVITY_SCREEN',
  ACCCOUNT_SCREEN: 'ACCOUNT_SCREEN',
});
