export default Object.freeze({
  LOGIN_SCREEN: 'LOGIN',
  RETRIEVE_ACCOUNT_SCREEN: 'RETRIEVE_ACCOUNT_SCREEN',
  CHECK_YOUR_MAIL_SCREEN: 'CHECK_YOUR_MAIL_SCREEN',
  ONBOARDING_SCREEN_1: 'ONBOARDING_SCREEN_1',
  ONBOARDING_SCREEN_2: 'ONBOARDING_SCREEN_2',
  SETUP_PASSWORD_SCREEN: 'SETUP_PASSWORD_SCREEN',
  ONE_LAST_STEP_SCREEN: 'ONE_LAST_STEP_SCREEN',
  SET_UP_WALLET_PIN_SCREEN: 'SET_UP_WALLET_PIN_SCREEN',

  HOME_BOTTOM_TABS_NAVIGATOR: 'HOME_BOTTOM_TABS_NAVIGATOR',
  HOME_SCREEN: 'HOME_SCREEN',
  BOOKINGS_SCREEN: 'BOOKINGS_SCREEN',
  MY_HUB_SCREEN: 'MY_HUB_SCREEN',
  ACTIVITY_SCREEN: 'ACTIVITY_SCREEN',
  ACCCOUNT_SCREEN: 'ACCOUNT_SCREEN',
});
