export default Object.freeze({
  LOGIN_SCREEN: 'LOGIN',
  RETRIEVE_ACCOUNT_SCREEN: 'RETRIEVE_ACCOUNT_SCREEN',
  PRE_LOGIN_SUCCESS_SCREEN: 'PRE_LOGIN_SUCCESS_SCREEN',
  ONBOARDING_SCREEN_1: 'ONBOARDING_SCREEN_1',
  ONBOARDING_SCREEN_2: 'ONBOARDING_SCREEN_2',
  SETUP_PASSWORD_SCREEN: 'SETUP_PASSWORD_SCREEN',
  ONE_LAST_STEP_SCREEN: 'ONE_LAST_STEP_SCREEN',
  SET_UP_WALLET_PIN_SCREEN: 'SET_UP_WALLET_PIN_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  NEW_DEVICE_SCREEN: 'NEW_DEVICE_SCREEN',
  NEW_DEVICE_VERIFICATION_SCREEN: 'NEW_DEVICE_VERIFICATION_SCREEN',

  HOME_BOTTOM_TABS_NAVIGATOR: 'HOME_BOTTOM_TABS_NAVIGATOR',
  HOME_SCREEN: 'HOME_SCREEN',
  BOOKINGS_SCREEN: 'BOOKINGS_SCREEN',
  MY_HUB_SCREEN: 'MY_HUB_SCREEN',
  ACTIVITY_SCREEN: 'ACTIVITY_SCREEN',
  ACCCOUNT_SCREEN: 'ACCOUNT_SCREEN',

  // MY HUB PAGES
  BOOK_VISITOR_SCREEN: 'BOOK_VISITOR_SCREEN',
  CREATE_EVENTS_SCREEN: 'CREATE_EVENTS_SCREEN',
  GROUP_ACCESS_SCREEN: 'GROUP_ACCESS_SCREEN',
  BILLS_AND_COLLECTIONS_SCREEN: 'BILLS_AND_COLLECTIONS_SCREEN',
  BUY_POWER_SCREEN: 'BUY_POWER_SCREEN',
  PANIC_ALERT_SCREEN: 'PANIC_ALERT_SCREEN',
  HIRE_ARTISAN_SCREEN: 'HIRE_ARTISAN_SCREEN',

  // OTHER SCREENS
  ADD_MONEY_SCREEN: 'ADD_MONEY_SCREEN',
  ADD_MONEY_ATM_CARD_SCREEN: 'ADD_MONEY_ATM_CARD_SCREEN',
  TRANSACTION_LIST_SCREEN: 'TRANSACTION_LIST_SCREEN',
  TRANSACTION_DETAILS_SCREEN: 'TRANSACTION_DETAILS_SCREEN',

  // ACCOUNTS SCREEN
  MANAGE_PROFILE_SCREEN: 'MANAGE_PROFILE_SCREEN',
  MANAGE_HOUSEHOLD_SCREEN: 'MANAGE_HOUSEHOLD_SCREEN',
  ACCOUNT_SETTINGS_SCREEN: 'ACCOUNT_SETTINGS_SCREEN',
  HELP_CENTER_SCREEN: 'HELP_CENTER_SCREEN',
});
