export default Object.freeze({
  GET_PROFILE: 'GET_PROFILE',
  GET_DASHBOARD_PROPERTIES: 'GET_DASHBOARD_PROPERTIES',
  GET_WALLET_BALANCE: 'GET_WALLET_BALANCE',
  GET_WALLET_TRANSACTIONS: 'GET_WALLET_TRANSACTIONS',
  ELECTRICITY: 'ELECTRICITY',
});
