export default Object.freeze({
  GET_PROFILE: 'GET_PROFILE',
  GET_DASHBOARD_PROPERTIES: 'GET_DASHBOARD_PROPERTIES',
  GET_WALLET_BALANCE: 'GET_WALLET_BALANCE',
  GET_WALLET_TRANSACTIONS: 'GET_WALLET_TRANSACTIONS',
  ELECTRICITY: 'ELECTRICITY',
  GET_NOTIFICATION_PREFERENCES: 'GET_NOTIFICATION_PREFERENCES',
  GET_EMERGENCY_CONTACTS: 'GET_EMERGENCY_CONTACTS',
  GET_VISITOR_BOOKINGS: 'GET_VISITOR_BOOKINGS',
  GET_EVENT_BOOKINGS: 'GET_EVENT_BOOKINGS',
  GET_GROUP_ACCESS_BOOKINGS: 'GET_GROUP_ACCESS_BOOKINGS',
  GET_PROPERTY_DETAILS: 'GET_PROPERTY_DETAILS',
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
});
